### ISSUE TITLE
add mypy formatter 

### ISSUE THREAD

**Issue by caheredia** [pappasam/vim-filetype-formatter#8]
Hi, is it possible to add mypy as a formatter? 

No luck with this 
```
let g:vim_filetype_formatter_commands = {
      \ 'python': 'black -q - | isort -q - | mypy -',
      \ }
```

```
command: set -Eeuo pipefail; black -q - | isort -q - | mypy -
message: mypy: can't read file '-': No such file or directory
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pip
```

**Comment by pappasam** [comment]
Ah, this happens because mypy is not a formatter; it can be categorized as a linter (like pylint). By this, I mean that mypy does not read your code and return a newly formatted version of your code. Instead, mypy reads your code and returns messages / response codes indicating whether it has found any problems with the code you provided. Therefore, it never "formats" your code and only provides diagnostic messages about problems if finds.

Since "linters" and "static type checkers" like mypy are not formatters, they should not be used with `vim-filetype-formatter`. Instead, look into using something like <https://github.com/iamcco/diagnostic-languageserver> to integrate mypy with your language server diagnostics. See [here](https://github.com/iamcco/diagnostic-languageserver/wiki/Linters#mypy) for the mypy-specific configuration for diagnostic language server.

**Comment by caheredia** [comment]
@pappasam makes sense, thanks!
